//STUDENTS ACTIONS TYPES================================

export const GET_STUDENTS_LOADING = "GET_STUDENTS_LOADING"
export const GET_STUDENTS_SUCCESS = "GET_STUDENTS_SUCCESS"
export const GET_STUDENTS_ERROR = "GET_STUDENTS_ERROR"

export const ADD_STUDENT_LOADING = "ADD_STUDENT_LOADING"
export const ADD_STUDENT_SUCCESS = "ADD_STUDENT_SUCCESS"
export const ADD_STUDENT_ERROR = "ADD_STUDENT_ERROR"

export const UPDATE_STUDENT_LOADING = "UPDATE_STUDENT_LOADING"
export const UPDATE_STUDENT_SUCCESS = "UPDATE_STUDENT_SUCCESS"
export const UPDATE_STUDENT_ERROR = "UPDATE_STUDENT_ERROR"

export const EDIT_STUDENT_LOADING = "EDIT_STUDENT_LOADING"
export const EDIT_STUDENT_SUCCESS = "EDIT_STUDENT_SUCCESS"
export const EDIT_STUDENT_ERROR = "EDIT_STUDENT_ERROR"

export const DELETE_STUDENT_LOADING = "DELETE_STUDENT_LOADING"
export const DELETE_STUDENT_SUCCESS = "DELETE_STUDENT_SUCCESS"
export const DELETE_STUDENT_ERROR = "DELETE_STUDENT_ERROR"
